// backend/src/models.rs

use chrono::NaiveDateTime;
use serde::{Deserialize, Serialize};
use diesel::prelude::*;
use diesel::{Queryable, Insertable, AsChangeset};

// Import your schema generated by Diesel CLI.
// Adjust the path if your schema.rs is not directly under backend/src/
use crate::schema::{projects, about_pages, contact_messages};


// --- Project Model ---
// This struct is for querying data from the database.
// It includes all columns from the 'projects' table.
#[derive(Debug, Queryable, Serialize, Deserialize)]
#[diesel(table_name = projects)]
#[diesel(check_for_backend(diesel::pg::Pg))] // Adjust backend if not PostgreSQL (e.g., diesel::mysql::Mysql)
pub struct Project {
    pub id: i32,
    pub title: String,
    pub description: String,
    pub image_url: String,
    pub created_at: NaiveDateTime, // No #[diesel(skip_changeset)] here, as this struct doesn't derive AsChangeset
    // Add other fields from your 'projects' table here if any
}

// This struct is for inserting new projects into the database.
// It omits auto-generated fields like 'id' and 'created_at'.
#[derive(Insertable, Deserialize)]
#[diesel(table_name = projects)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct NewProject {
    pub title: String,
    pub description: String,
    pub image_url: String,
    // created_at is typically handled by the database upon insertion
}

// This struct is for updating existing projects.
// It derives AsChangeset and contains only the fields that can be updated.
// Fields are often Option<T> to allow partial updates.
#[derive(AsChangeset, Deserialize, Debug)]
#[diesel(table_name = projects)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct UpdateProject {
    pub title: Option<String>,
    pub description: Option<String>,
    pub image_url: Option<String>,
    // Do NOT include `id` or `created_at` here, as they are not meant to be changed via AsChangeset
    // If you had an `updated_at` field you wanted to set manually on update, it would go here:
    // pub updated_at: Option<NaiveDateTime>,
}


// --- AboutPage Model ---
#[derive(Debug, Queryable, Serialize, Deserialize)]
#[diesel(table_name = about_pages)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct AboutPage {
    pub id: i32,
    pub content: String,
    pub created_at: NaiveDateTime,
    // Add other fields from your 'about_pages' table here if any
}

#[derive(Insertable, Deserialize)]
#[diesel(table_name = about_pages)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct NewAboutPage {
    pub content: String,
}

#[derive(AsChangeset, Deserialize, Debug)]
#[diesel(table_name = about_pages)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct UpdateAboutPage {
    pub content: Option<String>,
}


// --- ContactMessage Model ---
#[derive(Debug, Queryable, Serialize, Deserialize)]
#[diesel(table_name = contact_messages)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct ContactMessage {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub message: String,
    pub sent_at: NaiveDateTime,
    // Add other fields from your 'contact_messages' table here if any
    pub is_read: bool, // Assuming you have an 'is_read' field for contact messages
}

#[derive(Insertable, Deserialize)]
#[diesel(table_name = contact_messages)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct NewContactMessage {
    pub name: String,
    pub email: String,
    pub message: String,
    // sent_at and is_read are often defaulted by the DB or set internally
}

// For ContactMessage, updates might be very limited (e.g., just marking as read)
#[derive(AsChangeset, Deserialize, Debug)]
#[diesel(table_name = contact_messages)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct UpdateContactMessage {
    pub is_read: Option<bool>,
    // You might add an optional updated_at field here if your DB tracks it.
}
